name = "public-albums"
main = "src/index.ts"
compatibility_date = "2025-06-03"

routes = [
    { pattern = "public-albums.ente.io", custom_domain = true }
]

tail_consumers = [
    { service = "tail" }
]
