name: Report a bug
description: Things that were working earlier but don't anymore
labels: []
body:
    - type: markdown
      attributes:
          value: |
              **Checklist**
              1. You've searched existing [issues](https://github.com/search?q=repo%3Aente-io%2Fente+&type=issues) and [discussions](https://github.com/search?q=repo%3Aente-io%2Fente+&type=discussions)
              2. It was working earlier (otherwise use [enhancements](https://github.com/ente-io/ente/discussions/categories/enhancements))
              3. It is not about self hosting (for those use [this](https://github.com/ente-io/ente/discussions/categories/q-a))
    - type: textarea
      attributes:
          label: Description
    - type: input
      attributes:
          label: Version
          description: The version can be seen at the bottom of settings.
          placeholder: e.g. v1.2.3
    - type: dropdown
      attributes:
          label: What product are you using?
          description: You can select multiple if needed.
          multiple: true
          options:
              - Ente Photos
              - Ente Auth
    - type: dropdown
      attributes:
          label: What platform are you using?
          description: You can select multiple if needed.
          multiple: true
          options:
              - Mobile - iOS
              - Mobile - Android
              - Mobile - FDroid
              - Desktop - Linux
              - Desktop - Windows
              - Desktop - macOS
              - Web - Firefox
              - Web - Chrome
              - Web - Safari
              - Web - Edge
              - Server
    - type: markdown
      attributes:
          value: Thank you! ❤️
